// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcvoefahdgainylkuksk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjdm9lZmFoZGdhaW55bGt1a3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzkzNzQsImV4cCI6MjA1ODc1NTM3NH0.YDL666M-d6yrPQirTEJiwMyxXPyC2n_BNYg52XlNFWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);